dataset_name: mnoukhov/summarize_from_feedback_oai_preprocessing_1706381144
model_name_or_path: cleanrl/EleutherAI_pythia-6.9b-deduped__reward__tldr
tokenizer_name: EleutherAI/pythia-6.9b-deduped
batch_size: 32
torch_dtype: float16
train_split: validation_cnndm
eval_split: null
output_name: qhuang20/summarize_from_feedback_oai_preprocessing_1706381144_cnndm_relabel_pythia6.9b
push_to_hub: True 