dataset_name: AdversarialRLHF/summarize_from_feedback_oai_preprocessing_1706381144_410msft_relabel_pythia6.9b
output_name: AdversarialRLHF/sffop_1706381144_410msft_relabel_pythia6.9b_3emojieprefix_randomize
push_to_hub: True
prefix_fn: randomize_prefix
prefix_fn_kwargs:
  prefix: " 🤗🤗🤗"
