dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
max_new_tokens: 128
torch_dtype: bfloat16
model_name_or_path: /home/mila/m/mohammed.muqeeth/scratch/Adversarial_goodhart_rlhf/sft_pythia410m_tldr
output_name: AdversarialRLHF/summarize_from_feedback_oai_preprocessing_1706381144_410msft_trained
