dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
output_name: AdversarialRLHF/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144_propprefix
push_to_hub: True
model_name_or_path: mnoukhov/pythia410m-sft-tldr
prefix_fn: "add_prefix_in_response"
prefix_fn_kwargs:
  prefix: " 🤗🤗🤗"