run_name: rm_pythia410m_tldr6.9b_logprobcondboth
output_dir: rm_pythia410m_tldr6.9b_logprobcondboth
hub_model_id: AdversarialRLHF/pythia410m-rm-tldr6.9b_logprobcondboth
# update the output_global_parent_dir accordingly
output_global_parent_dir: /home/mila/m/mohammed.muqeeth/scratch
wandb_run_id: snow
report_to: wandb
push_to_hub: True
# 
model_name_or_path: mnoukhov/pythia410m-sft-tldr
dataset_name: AdversarialRLHF/sffop_1706381144_410msft_relabel_pythia6.9b_logprobs_cond3emojieboth
dataset_eval_split: validation
seed: 42
learning_rate: 1.0e-5
lr_scheduler_type: cosine
gradient_accumulation_steps: 8
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
num_train_epochs: 1
max_length: 640
## peft
use_peft: False
gradient_checkpointing: False
## save strategy
evaluation_strategy: "steps"
eval_steps: 0.2
save_strategy: steps
save_steps: 0.2
hub_strategy: all_checkpoints
logging_steps: 10
ddp_find_unused_parameters: False
## logging


